prompt_dir: 'prompts_mistral'
save_dir: 'pred_mistral_ws41_st10'

model:
  model_provider: "Huggingface"  # "OpenAI", "Anthropic" or "Huggingface"
  model_name: "mistralai/Mistral-7B-Instruct-v0.2" #"Qwen/Qwen2.5-7B-Instruct"
  hopformer_config: 
    window_size: 41
    sim_threshold: 10
    softmax: 'normal'
    num_attn_sinks: 0
    hopf_type: max_fused
    exhale_after: 1.0
  snapkv:
    # window_size: 40
    # sim_threshold: 440
